flex:
  version: 0.2.6
  workflows:
    build:
      command: ./gradlew build
    update-template:
      command: battenberg upgrade --no-input
service:
  name: 'template-java-kotlin-library-test-template-update'
