flex:
  version: 0.5.0
  workflows:
    build:
      command: ./gradlew build
    update-template:
      command: battenberg upgrade --no-input
service:
  name: 'template-java-kotlin-library-test-template-update'
